# 基本概念（数据类型与输入输出） {#basic}

## 基本数据类型-变量

### 变量的命名和使用

Python中使用变量时，需要遵守一些规则和指南。违反这些规则将引发错误，而指南旨在让你编写的代码更容易阅读和理解。请务必牢记下述有关变量的规则。：

-   变量名只能包含字母、数字和下划线。变量名可以字母或下划线打头，但不能以数字打头，例如，可将变量命名为message_1，但不能将其命名为1_message。

-   变量名不能包含空格，但可使用下划线来分隔其中的单词。例如，变量名greeting_message可行，但变量名greetingmessage会引发错误。

-   不要将Python关键字和函数名用作变量名，即不要使用Python保留用于特殊用途的单词，如print。

-   变量名应既简短又具有描述性。例如，name比n好，student_name比s_n好，name_length比length_of_persons_name好。

-   慎用小写字母l和大写字母O，因为它们可能被人错看成数字1和0。

-   应尽量使用小写的Python变量名。

## 基本数据类型-数字

### 整数（int）

python中整数的定义与数学中的整数概念一致，没有取值范围限制

#### 整数的表示

2进制整数表示：以0b或者0B开头

```{python}
a=0b11
print(a)
```

8进制整数表示：以0o或者0O开头

```{python}
a=0o11
print(a)
```

16进制整数表示：以0x或者0X开头

```{python}
a=-0x11
print(a)
```

#### 整数的运算

数的运算：pow(x, y)：计算x的y次方

```{python}
pow(2, 10)
```

### 浮点数

浮点数指带有小数点及小数位的数

Python语言中对浮点数的表示存在限制，数值范围存在限制（上溢出，overflow），小数精度也存在限制（下溢出，underflow），这种限制与在不同计算机系统有关

常见形式：

-   最常用：小数 -- 0.12、-77.、-2.17
-   科学计数法：使用字母"e"或者"E"作为幂的符号，以10为基数 如a E b = a \* 10b

```{python}
i=4.3e2
j=4.3*pow(10,2)
print(i,j)
```

### 复数

python语言中的复数与数学中复数的概念一致

```{python}
z=1+5j
print(z.real,z.imag)
```

### 数字类型的操作

不同数字类型之间可以进行混合运算，运算后生成结果为最宽类型

整数之间运算，如果数学意义上的结果是小数（如不能整除），结果是浮点数；整数之间运算，如果数学意义上的结果是整数（包括整除），结果是整数； 整数和浮点数混合运算，输出结果是浮点数

### math库的调用

Python语言本身提供的数值运算符号有限，所以应用中我们经常使用Python提供的内置数学类函数库。 该库提供了4个数学常数和44个函数， pi、e、无穷大、非数值， 16个数值表示函数， 8个幂对数函数， 16个三角对数函数， 4个高等特殊函数。

```{python}
import math
x=math.sqrt(2)
print(x)
```

## 字符串

字符串就是一系列字符。在Python中，用引号括起的都是字符串，其中的引号可以是单引号，也可以是双引号，如下所示：

```{python}
"This is a string."

'This is also a string.'
```

### 字符串索引

-   Python中字符串索引从0开始，一个长度为L的字符串最后一个字符的位置是L-1

-   Python同时允许使用负数从字符串右边末尾向左边进行反向索引，最右侧索引值是-1

```{python}
greet='Hello,world'
print(greet[1])
print(greet[-1])
print(greet[-4])
```

**范围索引:**

可以通过两个索引值确定一个位置范围,返回这个范围的子串

– 格式：< string > [ < start >: < end > ]

– start和end都是整数型数值，这个子序列从索引start开始直到索引end结束，但不包括end的位置

```{python}
greet = 'Hello,world'
print(greet[0:3]) #输出位置0-2的子串
print(greet[2:])  #输出位置2往后的子串
print(greet[:4])  #输出位置0-3的子串
print(greet[2:-3]) #输出前面去掉两字符，后面去掉三字符的字符串
```

### 字符串的操作

#### 变换大小写

```{python}
name = "love stats"  
print(name.title())
```

```{python}
name = "Love stats"  
print(name.upper())
```

```{python}
name = "Love stats"  
print(name.lower())
```


